@host = http://localhost:4674/api

###
GET {{host}}/task?uid=4

###
GET {{host}}/task/all


###
POST {{host}}/task/new
Content-Type: application/json

{
    "title": "1",
    "priority": 1,
    "steps": [
        {
            "id": 1,
            "value": "11"
        }
    ]
}

###
PUT {{host}}/task/updateTask
Content-Type: application/json

{
    "uid":4,
    "title":"test integration",
    "priority":"3",
    "status":"Changed",
    "steps": [
   
  ]
}
###
DELETE {{host}}